name: pages

on:
  push:
    branches:
      - main
    paths:
      - web/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: "16"

    - name: Install & Build
      run: yarn && yarn build
      working-directory: ./web
      env:
        VITE_API_HOST: https://v2202104145753149514.ultrasrv.de:4200

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./web/dist
